FROM node:20 as build-stage
RUN npm install -g pnpm
WORKDIR /app
COPY package*.json .
RUN pnpm install
COPY src ./src
COPY static ./static
COPY jsconfig.json .
COPY svelte.config.js .
COPY vite.config.js .
RUN pnpm run build

FROM nginx:1.21.1-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
